### ISSUE TITLE
Bug: Prevent same static node being added to multiple clusters

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#1141]
### Current Behaviour
Currently it seems like nothing prevents the same static node being a part of multiple cluster manifests. We should prevent such a scenario from happening.

### Expected Behaviour
If a node is added into a cluster before it's properly decommissioned from the previous cluster, the operation will not happen until a successful decommissioning is done in the first place. Respective log error message is emitted.

**Comment by JKBGIT1** [comment]
We need to reproduce this before actually implementing it.
1. Add static node to the `cluster A`
2. Remove static node from `cluster A`
3. Add the static node to the `cluster B`

**Comment by cloudziu** [comment]
Hey, I wasn't able to reproduce that issue. I was trying with scenarios that @JKBGIT1 described where I was creating a cluster with static nodes, removing it and adding ato a new cluster. Done that multiple times but without success.

**Comment by cloudziu** [comment]
As far as I could not reproduce the issue by removing and adding the same static node to different clusters, I created two clusters using the same static node. In this scenario, one of the clusters will always fail to add the node. 
Example scenario:
- create cluster `A`, with static node `X`
- create cluster `B`, with static node `X`
Kube-eleven won't add the static node to the cluster B, Kuber will fail.
But when I removed cluster `A`, removed the error from Claudie in cluster `B`, and reconciled - the static node was able to join cluster `B`.

As we discussed internally, when a static node is already a part of one cluster, Claudie should prevent adding it to a different one.

**Comment by Despire** [comment]
After testing different scenarios I was able to reproduce this (though not with 100% accuracy, but the issue is there)
One can reproduce this by first successfully building a cluster with a static node.
Then start building another different config with the same static node.
Once the second config is in the ansibler stage initiate the delete for the first config.

With this scenario the second config was able to be build but given the deletion of the first config wireguard was deleted on the static node

The cluster was in a sort-of usable way.
<img width="1410" alt="Screenshot 2024-01-02 at 15 30 06" src="https://github.com/berops/claudie/assets/30776544/45dcc95b-d236-44b7-bdc2-b2be21d106b6">

<img width="490" alt="Screenshot 2024-01-02 at 15 30 17" src="https://github.com/berops/claudie/assets/30776544/05d1edbf-6a38-40c9-aa56-e9d83a0227e7">

**Comment by Despire** [comment]
We should make sure that the same static node is not shared between clusters also across different configs.
