### ISSUE TITLE
Chore: Document latency-imposed limitations on cluster and PVC replication topology

### ISSUE THREAD

**Issue by bernardhalas** [berops/claudie#1192]
### Description
Add a section in the docs that would prevent the user from deploying Claudie in topologies where we know it would not operate reliably. These are specifically latency-imposed limitations, which tie to:
- findings summarized in [our blog post](https://www.berops.com/blog/evaluating-etcds-performance-in-multi-cloud)
- guidance from the Longhorn engineering team posted in a [github issue](https://github.com/longhorn/longhorn/issues/1691#issuecomment-729633995)

### Exit criteria

- [x] New section added into docs.claudie.io
- [x] Guidance about control-plane node distribution
- [x] Guidance about longhorn replica latency requirements
- [x] Guidance about PV mount latency requirements

**Comment by JKBGIT1** [comment]
IMO this can be used in this part of the documentation.

Longhorn settings to workaround a high latency issue when using RWX volumes. The settings are as follows and I changed their values through the Longhorn UI:

- Timeout R/W replicas - max 30 secs
- HTTP timeout - max 120 secs
- CPU guaranteed for Longhorn manager pods on each node - max 40%

Thanks to maximizing these settings I managed to mount a RWX volume that has a share-manager pod in **Hong Kong** and a replica in **Europe** + a running workload pod in **Europe**. However, there are some requirements on the k8s nodes and the maximum size of the volumes. For example, I didn't manage to mount a volume, when I used `GCE e2-medium` instances (2vCPU shared, 4GB RAM) as my k8s nodes, but I managed to mount that RWX volume when I replaced them with `e2-high-cpu-4` (4vCPU, 4GB RAM) or `e2-standard-2` (2vCPU, 8GB RAM).

Using machines with higher resources and maximizing these settings doesn't necessarily guarantee successful mounting, because when I was mounting volumes from 1GiB to 3GiB everything went smoothly, even when mounting a couple of them at once. However, when I increased the size of the volumes to 10GiB `e2-standard-2` didn't manage to mount 2 or more RWX volumes at once (this means that I needed to mount these volumes one by one).

One more note, in the case of `e2-high-cpu-4`, I didn't have to increase the CPU guaranteed for Longhorn manager pods on each node to 40% to mount the 1GiB to 3GiB RWX volumes.

I think the **conclusion** is that maximizing the Longhorn timeout settings can help to workaround the high latency issue when mounting RWX volumes, but it is really resource-hungry and it also depends on the size of the RWX volume + the total number of the RWX volumes that are attaching at once.

BTW it takes from 7 to 10 minutes to mount a RWX volume in this scenario - a share-manager pod in **Hong Kong** and a replica in **Europe** + a running workload pod in **Europe**
