### ISSUE TITLE
Bug: gRPC Connectivity Disruption Issue Between Services

### ISSUE THREAD

**Issue by cloudziu** [berops/claudie#1294]
There's an issue with the gRPC connection between services. The connection between them gets dropped after some time. This is particularly strange because the connection loss occurs even on a single-node cluster where no other applications are installed, and physically, the service pods shouldn't have any network issues.

Related issues: #1292 #1287

**Comment by bernardhalas** [comment]
I've seen this when running Claudie in `kind`.

**Comment by MiroslavRepka** [comment]
Does this happen when services are running some task? Maybe resource usage can be the culprit. For instance I see builder requests suspiciously low.

**Comment by cloudziu** [comment]
Hey @MiroslavRepka it can happen when an idle claudie instance is deployed.

**Comment by bernardhalas** [comment]
> Does this happen when services are running some task? Maybe resource usage can be the culprit. For instance I see builder requests suspiciously low.

Yes, this also happens in scenarios with enough CPU headroom, which leaves the `specs.resources.cpu.requests` configuration out.

**Comment by Despire** [comment]
Might be resolved by https://github.com/berops/claudie/pull/1313 and https://github.com/berops/claudie/pull/1293

**Comment by JKBGIT1** [comment]
I worked on this and below are the most important findings:
- The restart of the `context-box` starts an endless queue of the `claudie-operator`’s restarts. The `claudie-operator` first restarts ~1 minute after the `context-box` restart and then restarts every ~30 minutes due to the lost connection to the `context-box` in the health check (the `context-box` is constantly ready after the restart). BTW, the `scheduler` also connects to the `context-box` in its health check, but it doesn’t start restarting when the `context-box` restarts. https://github.com/berops/claudie/issues/1323
- `context-box` restarts, when it can’t ping Mongodb. This happens to me when I deploy Claudie on a new management cluster and it has to pull all the images... https://github.com/berops/claudie/issues/1325
- `ansibler`, `kuber`, and `kube-eleven` can't experience any gRPC connectivity disruption, because they don't have custom health check functions.
- `terraformer` depends only on the Dynamo table and MINIO bucket, which leaves it from the gRPC connectivity disruption to other services. https://github.com/berops/claudie/issues/1326

I'm closing this in favor of https://github.com/berops/claudie/issues/1323 https://github.com/berops/claudie/issues/1325 https://github.com/berops/claudie/issues/1326
