### ISSUE TITLE
Feature: Monitoring

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#417]
### Motivation:
It seems Claudie will be required to offer some sort of a monitoring solution out of the box.

Rough ideas:
- node exporters for LBs (or even K8s nodes?)
- default Prometheus stack deployed to the cluster, including grafana with some default dashboards
- auto-managed Prometheus Service Monitors to scrape the LBs
- inputManifest flag to control whether the monitoring gets deployed or not
- the whole monitoring feature might later be taken advantage of while designing autoscaling and self-healing

This will be a relatively big undertaking, and we aren't quite sure yet of neither the scope, nor the implementation.

### Description:
Come up with a complete architectural design of how Claudie will do monitoring - already in mind with potential future implementations of Autoscaling, Self-healing, and similar features.

### Exit criteria:
- [ ] Propose and agree upon architectural design of Monitoring in Claudie
- [ ] Open subtasks
- [ ] Ensure all subtasks are completed, and that Claudie now has monitoring as originally intended

**Comment by MarioUhrik** [comment]
Triggered via https://github.com/Berops/claudie/issues/408

**Comment by cloudziu** [comment]
We agreed that a full blown monitoring solution is not necessary at this moment and we will sick only to #408.

**Comment by bernardhalas** [comment]
I'll just add more context why did we agree on closing this epic.

The question was whether to add a full-blown monitoring solution (Prometheus, Alertmanager, Grafana) or just the node-exporters so that the user can plug their monitoring  stack to Claudie-made clusters.

The perspective is the following. What is the primary user-group of Claudie?
- Smaller developer teams would like to get a ready-made solution.
- SRE engineers and platform engineers using Claudie as a K8s cluster provisioner and orchestrator, would prefer to plug into their existing automation infrastructure.

So we've decided not to tackle the monitoring stack, but we'll keep both the above options open for now. That means we'll add node-exporters on the LB (they will be needed either way) and any monitoring deployments will be done manually. There are several projects that could be used out-of-the-box.
