### ISSUE TITLE
Add FAQ document explaining what Claudie is and what Claudie isn't

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#718]
To clear the doubts. To explain, where Claudie makes sense and indicate where it doesn't.

```
an example:
Q: Does Claudie makes sense as a pure K8s orchestration on a single cloud-provider IaaS?
A: It will work well, however Claudie, being opinionated and focused on multi-cloud scenarios will come with its own set of downsides. The main one being the necessity to get a public IPv4 address for each node. However, if you're are building the cluster and you'd like to keep the options open to use some of the multi-cloud features in future (i.e. workload migration to another cloud provider, or extending the cluster with nodepools from another cloud provider in a multi-cloud fashion), then Claudie is the cluster provisioner for you.
```

@bernardhalas  agreed to help with creating the questions

The purpose of this task is to gather the questions and their answers into a markdown doc, put it next to https://github.com/berops/claudie/blob/master/docs/use-cases, and have this referenced from within ideally here https://github.com/berops/claudie/blame/master/README.md#L28

**Comment by bernardhalas** [comment]
The proposed list of questions:
1. Does Claudie make sense as a pure K8s orchestration on a single cloud-provider IaaS?
2. Is there any networking performance impact due to the fact that the traffic is encrypted between the nodes?
4. Does each node really need a public IP address?
5. Is a GUI planned?
6. Is a ClusterAPI provider planned?
7. Is a Terraform provider planned?
8. What is the roadmap for adding support for new cloud IaaS providers?
