### ISSUE TITLE
New ultra-detailed "getting started" section

### ISSUE THREAD

**Issue by MarioUhrik** [berops/claudie#835]
The current getting started section isn't truly foolproof, e.g. it takes some GCP skill to create the correct service account key or the correct DNS zone.

We can add a new document that'll do all these steps in a copy-pastable way via the CLI.
In the beginning, the user starts with just having admin access to GCP.
In the end, the user will have a running Claudie cluster in GCP.

This way, the skill required in order to "get started" with Claudie is reduced to bare minimum, thus optimizing the potential for people giving Claudie a shot.

This document can be referenced from the README.
The old "getting started" section can be renamed, in order to distinguish between the high-level operational steps we have there now, and between the super-detailed super-specific guide produced by this task.

**Comment by bernardhalas** [comment]
Hi guys, I thought about how to design this, with the best UX in mind. Let me know what you think about the following proposal.

There will be one quickstart guide. This quickstart guide will create a smooth flow for getting a cluster up quickly.

Quickstart guide will contain sections. The sections could be as follows:

# Prepare management cluster
KinD deployment commands could be proposed here.

# Deploy Claudie
Using the existing copy/paste shell script.

# Input manifest
Existing example manifest to be referenced.

# Available providers
The most challenging part. This would contain:
1. List of providers (as links where user will click on the one (s)he is interested in and that would bring him/her to a page described in point 2. and 3.)
2. Each provider page will have the "Quickstart" sub-section with CLI commands for quick and painless experience within the quickstart usage philosophy (with ready-made copy/paste CLI commands).
3. Each provider page will also have "Provider details" sub-section which would elaborate on the provider specifics and link the relevant provider documentation for deeper understanding.

# Connect to created clusters
How to get the kubeconfig

# Troubleshooting
A section on:
- manifest validation info
- workflow sequence (FE, c-box, builder, terraformer,...) so that a user can try to see which service has complained and switch on debug logs accordingly
- how to switch on debug logs
