### ISSUE TITLE
Chore: Deploying Claudie with kubectl -k fails with particular versions of kustomize

### ISSUE THREAD

**Issue by JKBGIT1** [berops/claudie#982]
### Description
Some particular versions of `kubectl` just contain a packaged binary of a particular version of `kustomize`. User doesn't have much control over it, so running `kubectl apply -k claudie` ends up with error in this case.

### Exit criteria
To solve this we should explicitly declare our supported version of `kustomize` in the appropriate spot in the docs/readme/kustomization.yaml comment.

- [ ] declared supported version of `kustomize` in docs/readme/kustomization.yaml comment.

**Comment by MarioUhrik** [comment]
We've agreed to solve this differently.
In the release pipeline, we're going to "render" the manifests via `kustomize build`, and include the rendered huge yaml in the release. 
The official way to install Claudie will be via `kubectl -f ${URL_RENDERED_YAML_PARTICULAR_RELEASE}`.

This will enable us to bypass kustomize on the user side. Thus, this issue is also solved.
